version: "3.1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4g -Xmx4g # JVM 堆内存配置
      - bootstrap.memory_lock=true # 锁定物理内存，禁止 swap
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN # 设置为中文界面
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  es-data:
    driver: local